### ISSUE TITLE
type error  run on python3.6 

### ISSUE THREAD

**Issue by fingerecho** [CSIRO-enviro-informatics/proms#3]
When I run the code of this line "io.StringIO(self.request.data)", in routes/class_reports.py and routes/class_reportingsystems.py ,it occured , "initial_value must be str or None, not byte", Because the initial function of the   " io.StringIO()" could not accept the  bytes's type of the "request.data" , I use the version of the 3.6 python
The echo like this:
`b'The ReportingSystem posted is not valid for the following reasons: The serialised data cannot be parsed. Is it valid RDF?, Parser says: initial_value must be str or None, not bytes.'`
When I tried to run it on Ipython with some tests, it give me the same like this 
TypeError: initial_value must be str or None, not bytes
So the code could not run well on python3.6

**Comment by fingerecho** [comment]
another code error :         data = {'update': 'INSERT DATA { GRAPH <' + named_graph_uri + '> { ' + g.serialize(format='nt') + ' } }'}   , because of the type of g.serialize(format="nt") is bytes , but the data is string , so it must be corrected to g.serialize(format="nt").decode("utf-8") , this line

**Comment by nicholascar** [comment]
Thanks for the Issue. I will look at this ASAP. Nick

**Comment by nicholascar** [comment]
Regarding the StringIO error: I think you must be using an old version of the codebase as the current versions of the class_reports.py & class_reportingsystems.py files you mentioned are not in the routes/ folder but in controller/ (see https://github.com/CSIRO-enviro-informatics/proms/blob/master/controller/class_reports.py & https://github.com/CSIRO-enviro-informatics/proms/blob/master/controller/class_reportingsystems.py). Also, neither of those files have a line like "io.StringIO(self.request.data)" in them, both have the correct  io.StringIO(self.request.data.decode('utf-8')) (e.g. https://github.com/CSIRO-enviro-informatics/proms/blob/28d114ce745e4482f91478b8c2c7374550063e04/controller/class_reports.py#L31). 

For the error you report  about `data = {'update': 'INSERT DATA { GRAPH`, I also see that line with the the correct "decode("utf-8")" in it, see .

Can you please tell me what branch you're running? Are you perhaps using the old branch 310? You should use Master as that's the update branch and it works with Python 3.6. I will remove that old 310 branch now.

**Comment by fingerecho** [comment]
Thank you , I got it

**Comment by fingerecho** [comment]
The second question, I dowloaded the Resource from    https://github.com/CSIRO-enviro-informatics/proms/archive/v4.0.tar.gz    , then I extracted it , then I found the bug on the line of 36 .

**Comment by nicholascar** [comment]
OK, new release needed so I'll create an Issue for that but close this one.
